// mcp-roster.mjs — render the full MCP tool roster to docs/MCP-ROSTER.md.
//
// THE ONE PLACE to see every verb the doors offer (founder ask, 2026-08-19:
// "a single place where I can easily see the full roster of mcp verbs,
// ESPECIALLY the apex world and everything in it"). The door itself
// (tools/list) stays the runtime truth; this file is its readable rendering —
// regenerate in the commit that changes any tool:
//
//   node tools/mcp-roster.mjs
//
// The apex `world` verb's ACTION roster is dispatch-derived here (action →
// flat tool), with the caveat printed in the doc: the live per-standpoint
// action list (with class-mark blurbs and dials) is the bare `world` call's
// answer — actions appear because class marks grant them, and law can move.

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const { TOOLS, WRITE_TOOLS, DELISTED } = await import("../src/mcp.mjs");
const { DISPATCHABLE, dispatchToolFor, WORLD_READ_FIELDS } = await import("../src/world-apex.mjs");
const { classRoster } = await import("../src/world-classes.mjs");

// ── THE FLOOR GUARD (Wright's fix round, 2026-08-26) ───────────────────────
//
// `world_leave_mark`'s `class` enum is not written in this repo. It is read
// live from the world store by `world-classes.mjs § classRoster`, and when that
// store is missing, unreadable, or holds no class marks, the roster falls back
// to a hard FLOOR of two names — and says so, returning `source: "floor"` and a
// `disclosed` sentence naming exactly what happened.
//
// `classNames()` drops that sentence and hands back only the set, so this
// generator used to render the floor into the page as if it were the live enum:
// about 130 names collapsing to 2, silently, on any machine without a hydrated
// world. A doc that gets WORSE by following its own "regenerate in the commit
// that changes any tool" instruction is a trap, and it is the likeliest reason
// this page had drifted a whole day behind the door it renders.
//
// THE INVARIANT, in Wright's words: the rendered roster can never silently
// present the fallback as the live enum. So:
//
//   • by default, a floor roster REFUSES — nothing is written, the disclosure
//     is printed, and the exit code is non-zero, because a doc build that
//     cannot see the record should fail loudly rather than publish a smaller
//     truth;
//   • `--allow-floor` writes anyway, and stamps the disclosure into the page
//     itself, so a reader of the artifact learns what the generator knew.
//
// The door already told the truth. This is the renderer learning to repeat it.
const ROSTER = classRoster();
const ALLOW_FLOOR = process.argv.includes("--allow-floor");
if (ROSTER.source === "floor" && !ALLOW_FLOOR) {
  console.error("REFUSING TO WRITE docs/MCP-ROSTER.md — the class roster is standing on its floor.");
  console.error(`  ${ROSTER.disclosed}`);
  console.error(`  The page would render ${ROSTER.roster.size} classes where the record holds many more,`);
  console.error("  and nothing in it would say so. Hydrate a world store and run again:");
  console.error("    npm run hydrate:world            (or --db / WORLD_STORE_DB at a store you trust)");
  console.error("  To publish anyway WITH the disclosure printed on the page: --allow-floor");
  process.exit(1);
}

const fence = (s) => String(s ?? "").replaceAll("|", "\\|").replaceAll("\n", " ");
const firstSentences = (s, n = 2) => {
  const parts = String(s ?? "").split(/(?<=\.)\s+/);
  return parts.slice(0, n).join(" ");
};

const lines = [];
lines.push("# The MCP roster — every verb at the doors");
lines.push("");
lines.push("*GENERATED by `tools/mcp-roster.mjs` — regenerate in the commit that changes any tool. The door's own `tools/list` is the runtime truth; this page is its readable rendering.*");
lines.push("");
lines.push(`*${TOOLS.length} tools · rendered ${new Date().toISOString().slice(0, 10)}*`);
lines.push("");
// The slim, spelled out where a newcomer lands: the live tools/list advertises
// only the listed verbs, while this page renders every defined verb — including
// delisted ones, which still answer for cached clients. Each verb below carries
// its badge, so the "50 tools" headline never reads as a stale tools/list.
lines.push("*The live `tools/list` advertises a slim subset — the listed verbs. This page renders every defined verb, including delisted ones, which still answer for cached clients (delisting is listing-only: unadvertised, never unplugged). Each verb below is badged `listed` or `delisted · still answers`.*");
lines.push("");
// The stamp, only when the roster is degraded — a reader of the artifact is
// owed what the generator knew, and a page that reads normally on a normal run
// is what keeps this line meaningful when it does appear.
if (ROSTER.source === "floor") {
  lines.push(`> ⚠ **The \`class\` enum below is NOT the live roster.** ${ROSTER.disclosed}`);
  lines.push(">");
  lines.push("> It is rendered here only because this run was given `--allow-floor`. The door's own `tools/list` remains the truth; re-render from a machine with a hydrated world store before trusting the class list.");
  lines.push("");
}

// ── the apex first, since it is the door the founder asked after ───────────
lines.push("## The apex: `world` — one verb, and everything in it");
lines.push("");
lines.push("A bare `world` call (with `handle:`) answers where you stand, who is about, and **`actions:` — the live roster of every act your standpoint affords**, each with its class-mark blurb, dials, and fields. That live answer outranks this table: actions appear because class marks grant them, and law moves at crossings.");
lines.push("");
lines.push("The dispatch table (action → the flat tool that carries its arguments):");
lines.push("");
lines.push("| apex action | dispatches to |");
lines.push("|---|---|");
for (const a of DISPATCHABLE) lines.push(`| \`${a}\` | \`${dispatchToolFor(a) ?? "— (argument-free: do: performs it directly)"}\` |`);
lines.push("");
// The shadow reads' own fields (postmark#3138): `read:` narrows with args:,
// and a field that lives only here (`who` on the walk read) had no page that
// named it. Rendered from the same table the door validates against.
lines.push("The shadow reads' narrowing fields (`world { read: <action>, args: { … } }`; a read never performs):");
lines.push("");
lines.push("| read | field | what it does |");
lines.push("|---|---|---|");
for (const [a, props] of Object.entries(WORLD_READ_FIELDS))
  for (const [k, p] of Object.entries(props ?? {})) lines.push(`| \`${a}\` | \`${k}\` | ${fence(p.description)} |`);
lines.push("");

// ── the flat roster ─────────────────────────────────────────────────────────
lines.push("## The flat tools, whole");
lines.push("");
for (const t of TOOLS) {
  const badge = WRITE_TOOLS.has(t.name) ? " · **write (credentialed)**" : " · read";
  // The slim, per verb: DELISTED mirrors the production (apex-on) tools/list —
  // a verb absent from the set is one the live list advertises.
  const listedBadge = DELISTED.has(t.name) ? "delisted · still answers" : "listed";
  lines.push(`### \`${t.name}\`${badge} · *${listedBadge}*`);
  lines.push("");
  lines.push(firstSentences(t.description, 3));
  lines.push("");
  const props = t.inputSchema?.properties ?? {};
  const required = new Set(t.inputSchema?.required ?? []);
  const names = Object.keys(props);
  if (!names.length) { lines.push("*No arguments.*"); lines.push(""); continue; }
  lines.push("| field | type | notes |");
  lines.push("|---|---|---|");
  for (const k of names) {
    const p = props[k];
    const type = p.enum ? p.enum.map((v) => `\`${v}\``).join(" \\| ") : (p.type ?? "");
    const req = required.has(k) ? "**required** — " : "";
    lines.push(`| \`${k}\` | ${fence(type)} | ${req}${fence(firstSentences(p.description, 1))} |`);
  }
  lines.push("");
}

// `--out` exists so the floor guard above can be FALSIFIED without a test
// writing into the repo's own docs. Default is unchanged.
const outArg = process.argv.indexOf("--out");
const out = outArg !== -1 && process.argv[outArg + 1]
  ? process.argv[outArg + 1]
  : join(here, "..", "docs", "MCP-ROSTER.md");
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, lines.join("\n") + "\n");
console.log(`wrote ${out} — ${TOOLS.length} tools, ${DISPATCHABLE.length} apex actions`);
